-- ═══════════════════════════════════════════════════════════════
-- 002 — Tablas de actividad: reuniones, llamadas, oportunidades
-- Sincronizadas desde GHL via sync/scripts/
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS reuniones (
  id                      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ghl_appointment_id      TEXT,
  titulo                  TEXT,
  fecha_reunion           TIMESTAMP,
  fecha_agendada          TIMESTAMP,
  starts_at               TIMESTAMPTZ,
  ends_at                 TIMESTAMPTZ,
  appointment_at          TIMESTAMPTZ,
  hora_reunion            TIME,
  origen_reunion          TEXT        NOT NULL DEFAULT 'ghl_calendar',
  cliente_id              BIGINT,
  cliente_slug            TEXT,
  sdr_id                  BIGINT,
  sdr_slug                TEXT,
  contacto_id             BIGINT,
  contacto                TEXT,
  ghl_contact_id          TEXT,
  appointment_contact_id  TEXT,
  ghl_owner_user_id       TEXT,
  location_id             TEXT,
  ghl_calendar_id         TEXT,
  empresa                 TEXT,
  pais                    TEXT,
  telefono                TEXT,
  email                   TEXT,
  cargo                   TEXT,
  industria               TEXT,
  direccion_reunion       TEXT,
  opportunity_id          TEXT,
  -- estado y validación
  estado                  TEXT,
  estado_reunion          TEXT,
  estado_validacion       TEXT,
  valida                  BOOLEAN,
  es_valida               BOOLEAN,
  excluida                BOOLEAN     DEFAULT false,
  reagendada              BOOLEAN,
  cancelada               BOOLEAN,
  no_show                 BOOLEAN,
  pendiente_validacion    BOOLEAN,
  fecha_reunion_estimada  BOOLEAN     NOT NULL DEFAULT false,
  motivo_rechazo          TEXT,
  motivo_no_valida        TEXT,
  fecha_validacion        DATE,
  observacion             TEXT,
  notas                   TEXT,
  asignacion_estado       TEXT,
  asignacion_fuente       TEXT,
  raw_data                JSONB       NOT NULL DEFAULT '{}',
  synced_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS reuniones_ghl_appointment_id_key ON reuniones (ghl_appointment_id);

CREATE TABLE IF NOT EXISTS llamadas (
  id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ghl_call_id        TEXT,
  conversation_id    TEXT,
  fecha              TIMESTAMP,
  started_at         TIMESTAMPTZ,
  hora               TIME,
  cliente_id         BIGINT,
  cliente_slug       TEXT,
  sdr_id             BIGINT,
  sdr_slug           TEXT,
  contacto_id        BIGINT,
  ghl_contact_id     TEXT,
  ghl_owner_user_id  TEXT,
  location_id        TEXT,
  duracion_segundos  INTEGER,
  duracion_minutos   NUMERIC,
  resultado          TEXT,
  direction          TEXT,
  direccion          TEXT,
  status             TEXT,
  mensaje_tipo       TEXT,
  source             TEXT,
  telefono           TEXT,
  asignacion_estado  TEXT,
  asignacion_fuente  TEXT,
  raw_data           JSONB       NOT NULL DEFAULT '{}',
  synced_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS llamadas_ghl_call_id_key ON llamadas (ghl_call_id);

CREATE TABLE IF NOT EXISTS oportunidades (
  id                     UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  ghl_opportunity_id     TEXT        NOT NULL UNIQUE,
  ghl_contact_id         TEXT,
  ghl_owner_user_id      TEXT,
  cliente_slug           TEXT,
  location_id            TEXT,
  sdr_slug               TEXT,
  nombre                 TEXT,
  valor_monetario        NUMERIC,
  pipeline_id            TEXT,
  pipeline_name          TEXT,
  pipeline_stage_id      TEXT,
  pipeline_stage_uid     TEXT,
  pipeline_stage_name    TEXT,
  stage_category         TEXT,
  estado                 TEXT,
  fuente                 TEXT,
  is_meeting_stage       BOOLEAN     NOT NULL DEFAULT false,
  is_valid_meeting       BOOLEAN,
  probabilidad_forecast  NUMERIC,
  probabilidad_efectiva  NUMERIC,
  contacto_nombre        TEXT,
  contacto_empresa       TEXT,
  contacto_email         TEXT,
  contacto_telefono      TEXT,
  tags                   JSONB       NOT NULL DEFAULT '[]',
  custom_fields          JSONB       NOT NULL DEFAULT '[]',
  raw_data               JSONB       NOT NULL DEFAULT '{}',
  ghl_created_at         TIMESTAMPTZ,
  ghl_updated_at         TIMESTAMPTZ,
  last_status_change_at  TIMESTAMPTZ,
  last_stage_change_at   TIMESTAMPTZ,
  synced_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
